spring.application.name=springJwt
server.port=8081

# Spring DataSource Connection
spring.datasource.url=jdbc:mysql://localhost:3306/Jwt
spring.datasource.username=root
spring.datasource.password=Menna123#

# Spring JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=mysql
