pipeline {
    agent any

    tools {
        maven 'maven' 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Compile') {
            steps {
             
                dir('Task18_Security_4') {
                    echo 'Building Spring Security Project...'
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('Task18_Security_4') {
                    echo 'Running Spring Unit Tests...'
                    bat 'mvn test'
                }
            }
        }
    }
}